name: Tests

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Run tests
        run: uv run pytest
      - name: Lint
        run: uv run pre-commit run -a
